import { v4 } from 'uuid';
// Массив c объектом данных позиций продукта для приготовления борща!!!
const productDataBorsch = [
  {
    id: v4(),
    position: 1,
    products: 'Говядина',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 62.5,
  },
  {
    id: v4(),
    position: 2,
    products: 'Картофель',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 62.5,
  },
  {
    id: v4(),
    position: 3,
    products: 'Капуста белокочанная',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 62.5,
  },
  {
    id: v4(),
    position: 4,
    products: 'Свекла',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 37.5,
  },
  {
    id: v4(),
    position: 5,
    products: 'Морковь',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 37.5,
  },
  {
    id: v4(),
    position: 6,
    products: 'Лук репчатый',
    quantity: 0,
    unit: 'шт',
    weightOfOneServing: 0.25,
  },
  {
    id: v4(),
    position: 7,
    products: 'Чернослив',
    quantity: 0,
    unit: 'шт',
    weightOfOneServing: 0.625,
  },
  {
    id: v4(),
    position: 8,
    products: 'Зелень петрушки',
    quantity: 0,
    unit: 'пуч',
    weightOfOneServing: 0.125,
  },
  {
    id: v4(),
    position: 9,
    products: 'Томат паста',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 0.25,
  },
  {
    id: v4(),
    position: 10,
    products: 'Соль',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 'по вкусу',
  },
  {
    id: v4(),
    position: 11,
    products: 'Масло растительное',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 0.25,
  },
  {
    id: v4(),
    position: 12,
    products: 'Вода',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 0.25,
  },
];

// Массив c объектом данных позиций продукта для приготовления блинов!!!
const productDataPancakes = [
  {
    id: v4(),
    position: 1,
    products: 'Молоко',
    quantity: 0,
    unit: 'л',
    weightOfOneServing: 0.12,
  },
  {
    id: v4(),
    position: 2,
    products: 'Яйца',
    quantity: 0,
    unit: 'шт',
    weightOfOneServing: 1,
  },
  {
    id: v4(),
    position: 3,
    products: 'Мука',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 35,
  },
  {
    id: v4(),
    position: 4,
    products: 'Масло сливочное, растопленное',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 5,
  },
  {
    id: v4(),
    position: 5,
    products: 'Соль',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 'по вкусу',
  },
  {
    id: v4(),
    position: 6,
    products: 'Сахар',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 5,
  },
];

// Массив c объектом данных позиций продукта для приготовления плова!!!
const productDataPilaf = [
  {
    id: v4(),
    position: 1,
    products: 'Баранина (молодая)',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 100,
  },
  {
    id: v4(),
    position: 2,
    products: 'Рис',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 90,
  },
  {
    id: v4(),
    position: 3,
    products: 'Морковь',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 90,
  },
  {
    id: v4(),
    position: 4,
    products: 'Зира',
    quantity: 0,
    unit: 'г',
    weightOfOneServing: 2,
  },
  {
    id: v4(),
    position: 5,
    products: 'Лук репчатый',
    quantity: 0,
    unit: 'шт',
    weightOfOneServing: 0.4,
  },
  {
    id: v4(),
    position: 6,
    products: 'Чеснок',
    quantity: 0,
    unit: 'шт',
    weightOfOneServing: 0.4,
  },
  {
    id: v4(),
    position: 7,
    products: 'Масло растительное',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 2,
  },
  {
    id: v4(),
    position: 8,
    products: 'Соль',
    quantity: 0,
    unit: 'ст.л',
    weightOfOneServing: 'по вкусу',
  },
  {
    id: v4(),
    position: 9,
    products: 'Вода',
    quantity: 0,
    unit: 'л',
    weightOfOneServing: 0.09,
  },
];

export { productDataBorsch, productDataPancakes, productDataPilaf };
